### ISSUE TITLE
ns3::Packet has no member named "Cleanup"

### ISSUE THREAD

**Issue by silmarilli** [rmartin5/aqua-sim-ng#12]
Hello, 
Trying to compile the git version of aqua-sim-ng with ns-3.27 and got the following:
../src/aqua-sim-ng/model/aqua-sim-mac-goal.cc: In member function ‘void ns3::AquaSimGoal::ProcessAckPkt(ns3::Ptr<ns3::Packet>)’:
../src/aqua-sim-ng/model/aqua-sim-mac-goal.cc:1161:10: error: ‘class ns3::Packet’ has no member named ‘Cleanup’
     pkt->Cleanup();
          ^~~~~~~
Any help is much appreciated. 
Thank you

**Comment by BigRabbit71** [comment]
Hi, 
the problem seems like to be related to the version of ns3, you can just comment this line, and replace with the following line:
`pkt = 0;`

Hope it helps.

**Comment by rmartin5** [comment]
Merged #13 . Thanks for the additions!
