### ISSUE TITLE
Wrong PER  calculation

### ISSUE THREAD

**Issue by donghuiyong** [rmartin5/aqua-sim-ng#33]
https://github.com/rmartin5/aqua-sim-ng/blob/78884179c2543466698521f0c0f9a24d899106b2/model/aqua-sim-modulation.cc#L70
shoule be
`return 1 - std::pow(1 - m_ber, pktSize);`

**Comment by dugdmitry** [comment]
Fixed in commit [8b3f1c9](https://github.com/rmartin5/aqua-sim-ng/commit/8b3f1c978d69ea2875b0cad2121683e233d09a2b)
