### ISSUE TITLE
No result when running examples

### ISSUE THREAD

**Issue by Duola-li** [rmartin5/aqua-sim-ng#4]
When I studied to run Aqua-Sim Next Generation. I can`t see any packet or any  simulation results. It just show "fin". Is there some code I need to add or change in the example?
![clipboard](https://user-images.githubusercontent.com/16505929/42811704-06d80212-89ee-11e8-967b-69f8224a0282.png)

**Comment by Duola-li** [comment]
There can`t see any transmission of packet in Graphical running。Is it right?
![image](https://user-images.githubusercontent.com/16505929/42879376-f7caa678-8ac2-11e8-9259-eb9b1316da54.png)

**Comment by Duola-li** [comment]
My question is how to see the result of simulation? 
Usually I run script in  UI method by "./waf --run xxx --vis" , but it is not effective run broadcastMAC_example.cc and named_data_example.cc ; There is no transmission of pocket. 
Use trace ?

**Comment by rmartin5** [comment]
Visualization (NS3's or Aqua3D) was never implemented on Aqua-Sim NG. You may be able to tweak the current work to fit to NS'3 API but I'm not quite sure the workable hours needed to achieve this. Beyond this you can use either the internal log as mentioned by @Atercatus or adjust the tracer to pull the data you need from within each protocol.
