### ISSUE TITLE
Transmission range

### ISSUE THREAD

**Issue by Duola-li** [rmartin5/aqua-sim-ng#8]
Is there a transmission range between the nodes? If so, what is the transmission range? Can I set it?

**Comment by BigRabbit71** [comment]
Hi,

First of all, you should set the propagation model as `AquaSimRangePropagation`.
After that, you could change the transmission range through `AquaSimNetDevice` like below:
```
Ptr<AquaSimNetDevice> newDevice = CreateObject<AquaSimNetDevice> ();
newDevice->GetPhy ()->SetTransRange (range);
```

Hope it helps.

**Comment by Duola-li** [comment]
It`s workable, thank you very much!
